name: YARA tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-test:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure PowerShell execution policy
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force

      - name: Install YARA (Chocolatey)
        shell: pwsh
        run: |
          choco install yara -y
        

      - name: Run YARA test harness
        shell: pwsh
        working-directory: tools
        run: |
          $possiblePaths = @(
            "C:\ProgramData\chocolatey\bin\yara64.exe",
            "C:\Program Files\Yara\yara64.exe",
            "C:\Program Files (x86)\Yara\yara64.exe"
          )
          $yaraPath = $possiblePaths | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $yaraPath) {
            Write-Error "YARA binary not found in expected paths: $($possiblePaths -join ', ')"
            exit 2
          } else {
            Write-Host "Using YARA binary at: $yaraPath"
          }
          .\run_tests.ps1 -YaraExe $yaraPath
      - name: Upload compiled rules artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled_rules.yar
          path: |
            compiled_rules.yar
            ../compiled_rules.yar
